# This workflow will run unit tests

name: Benchmark Postag Corpus
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  postag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev
          python -m pip install build wheel
      - name: Install repo
        run: |
          pip install .[sklearn]
      - name: Benchmark brown postag dataset
        run: |
          python scripts/benchmarks/brown.py
      - name: Benchmark treebank postag dataset
        run: |
          python scripts/benchmarks/treebank.py
      - name: Benchmark udep postag datasets
        run: |
          python scripts/benchmarks/udep.py
      - name: Commit benchmark
        uses: EndBug/add-and-commit@v9
        with:
          message: Brown benchmark
          add: 'models/*.md --force'
          pull: '--rebase --autostash'