# This workflow will run unit tests

name: (sklearn) Postag Universal Dependencies Corpus
on:
  push:
    branches:
      - dev
    paths:
      - 'scripts/training/postag/sklearn_treebank_brown_udep_dtree.py'
      - 'scripts/training/postag/sklearn_treebank_brown_udep_nb.py'
      - 'scripts/training/postag/sklearn_treebank_brown_udep_percep.py'
      - 'scripts/training/postag/sklearn_treebank_brown_udep_lsvc.py'
      - 'scripts/training/postag/sklearn_treebank_brown_npschat_mte_udep_nb.py'
  workflow_dispatch:

jobs:
  postag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev
          python -m pip install build wheel
      - name: Install repo
        run: |
          pip install .[sklearn]
      - name: Train Decision Tree postag
        run: |
          python scripts/training/postag/sklearn_treebank_brown_udep_dtree.py
      - name: Train Naive Bayes postag
        run: |
          python scripts/training/postag/sklearn_treebank_brown_udep_nb.py
      - name: Train Naive Bayes (more data) postag
        run: |
          python scripts/training/postag/sklearn_treebank_brown_npschat_mte_udep_nb.py
      - name: Train Perceptron postag
        run: |
          python scripts/training/postag/sklearn_treebank_brown_udep_percep.py
      - name: Train SVM postag
        run: |
          python scripts/training/postag/sklearn_treebank_brown_udep_lsvc.py
      - name: Commit models
        uses: EndBug/add-and-commit@v9
        with:
          message: Universal Dependencies auto-train (sklearn)
          add: 'models/ --force'
          pull: '--rebase --autostash'