# This workflow will run unit tests

name: (nltk) Postag floresta + mcmorpho Corpus
on:
  push:
    branches:
      - dev
    paths:
      - 'scripts/training/postag/nltk_brill_tagger_floresta_mcmorpho_udep.py'
      - 'scripts/training/postag/nltk_brill_tagger_floresta.py'
      - 'scripts/training/postag/nltk_brill_tagger_mcmorpho.py'
      - 'scripts/training/postag/nltk_brill_tagger_mcmorpho_udep.py'
  workflow_dispatch:

jobs:
  postag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev
          python -m pip install build wheel
      - name: Install repo
        run: |
          pip install .
      - name: Train floresta brill postag
        run: |
          python scripts/training/postag/nltk_brill_tagger_floresta.py
      - name: Train mcmorpho brill postag
        run: |
          python scripts/training/postag/nltk_brill_tagger_mcmorpho.py
      - name: Train mcmorpho (UDEP) brill postag
        run: |
          python scripts/training/postag/nltk_brill_tagger_mcmorpho_udep.py
      - name: Train floresta+mcmorpho (UDEP) brill postag
        run: |
          python scripts/training/postag/nltk_brill_tagger_floresta_mcmorpho_udep.py
      - name: Commit models
        uses: EndBug/add-and-commit@v9
        with:
          message: floresta+mcmorpho auto-train (nltk)
          add: 'models/* --force'
          pull: '--rebase --autostash'